name: Onomato
favicon: null
layout_spectrum: 0.9429653473198414
typography_spectrum: 0.7687507353257388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4086127826012671
  lightness: 0.5594646013341844
  saturation: 0.19048194657079875
  rhythmicContrast: 0.7141469952184707
purpose: []
