name: Onomato
favicon: null
layout_spectrum: 0.69211
typography_spectrum: 0.7282
title: Onomato Produtora
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29aaba'
    - '#efac17'
    - '#e46e22'
    - '#da227c'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
