name: Onomato
favicon: null
layout_spectrum: 0.07516
typography_spectrum: 0.5454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#474749'
    - '#ffffff'
    - '#7f8184'
    - '#cfd0d3'
    - '#000000'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.19048194657079875
  rhythmicContrast: 1
purpose: []
