name: Onomato
favicon: null
layout_spectrum: 0.07516
typography_spectrum: 0.7282
title: Produtora Sonora
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29aaba'
    - '#efac17'
    - '#e46e22'
    - '#da227c'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.19048194657079875
  rhythmicContrast: 1
purpose: []
